name: Maven Build Artifact

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - master
      - main

jobs:
  build:
    uses: valitydev/base-workflow/.github/workflows/maven-thrift-build.yml@v2
