name: Maven Build Artifact

on:
  push:
    branches:
      - master
      - main

jobs:
  build:
    uses: valitydev/java-workflow/.github/workflows/maven-thrift-deploy.yml@v2
    secrets:
      server-username: ${{ secrets.OSSRH_USERNAME }}
      server-password: ${{ secrets.OSSRH_TOKEN }}
      deploy-secret-key: ${{ secrets.OSSRH_GPG_SECRET_KEY }}
      deploy-secret-key-password: ${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }}
      mm-webhook-url: ${{ secrets.MATTERMOST_WEBHOOK_URL }}
